//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModel : DbContext
    {
        public DataModel()
            : base("name=DataModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<advogado> advogado { get; set; }
        public virtual DbSet<agendamento> agendamento { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<contrario> contrario { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<etapa> etapa { get; set; }
        public virtual DbSet<parceiro> parceiro { get; set; }
        public virtual DbSet<perfil> perfil { get; set; }
        public virtual DbSet<processo> processo { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
