//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projetoPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class processo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public processo()
        {
            this.etapa = new HashSet<etapa>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public int id_cliente { get; set; }
        public int id_usuario { get; set; }
        public int id_contrario { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual contrario contrario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<etapa> etapa { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
